import "./globals.css";
import Navbar from './component/Navbar'
import Footer from './component/Footer'



export const metadata = {
  title: "NextApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body> 
        <Navbar/> 
        <main className="min-h-screen">   
        {children}
        </main> 
        <Footer/>
      </body>
    </html>
  );
}
